Adding resume information
dstorbergjr/Resume pull request #3
Opened 2020-12-21 22:21 UTC by dstorbergjr

plz rev

2020-12-23 02:42 UTC, voodooGQ requested changes
Looks pretty good, have a few changes for you to make when you get some time.

2020-12-23 02:42 UTC, voodooGQ commented on index.html
> +    <div class="Summary">
Put the `<p>` tag below inside this `<div>` tag. So something like this:

```
<div class="Summary">
    <p>Detail-oriented Marine Corps........</p>
</div>
```

2020-12-23 02:42 UTC, voodooGQ commented on index.html
> +    <div class="Skills"></div>
Put the `<ul>` tag inside the `<div>` tag

2020-12-23 02:42 UTC, voodooGQ commented on index.html
> +    <ul>
`<ul>` list here looks really good

2020-12-23 02:42 UTC, voodooGQ commented on index.html
> +    <div class="Experience">
Generally we name classes based on a combination of "snake_case" or "kebab-case" style syntax. For instance this would be:

```
<div class="experience">
```

However, if you had a two word class it could look something like this:

```
<div class="my-experience">
```

or

```
<div class="my-experience_section">
```

2020-12-23 02:42 UTC, voodooGQ commented on index.html
> +      <h4>07/2019 – PRESENT</h4>
This isn't necessarily wrong here, but the `<h*>` style tags are usually displayed in a top down order, meaning you would see and `<h2>` after an `<h1>`. Another thing you can do here to produce a similar result is the following:

```
<span><strong>07/2019 - PRESENT</strong></span>
```

This is a `<span>` tag which is just a general purpose inline tag: https://www.w3schools.com/tags/tag_span.asp and inside that is a `<strong>` tag which will make the text bold.

Once we get into CSS we'll go into other methods to do this too.

2020-12-23 02:42 UTC, voodooGQ commented on index.html
> +      <h1>Law Enforcement Academy / Chippewa Valley Technical College</h1>
Try to only use 1 `<h1>` per webpage. It'll be easier to explain why in person :)

2020-12-23 02:42 UTC, voodooGQ commented on index.html
> +      <div class="volunteer opportunities"></div>
This is good, put a dash in between though :)

2020-12-23 02:42 UTC, voodooGQ commented on index.html
>      <!-- This is Paragraph -->
You can remove this line and the line below.

2020-12-25 23:12 UTC, dstorbergjr commented
corrected h elements, removed commented out lines, fixed class names - please review for merge

2020-12-25 23:15 UTC, voodooGQ approved these changes
LGTM

2020-12-25 23:20 UTC, merged